name: DeathSwap
main: main.DeathSwapMain
version: 1.0
api-version: 1.16

commands:
  deathswapstart:
    description: Start the game!
    usage: /<command>
    aliases: dsstart
  deathswapstop:
    description: Stop the game!
    usage: /<command>
    aliases: dsstop
  deathswapset:
    description: Set the swap time!
    usage: /<command> [time]
    aliases: dsset